# filename: auth_test2.ps1
# Code Generated by Sidekick is for learning and experimentation purposes only.
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$IdentityTenantSubdomain,
    [Parameter(Mandatory)][string]$PrivilegeCloudSubdomain,
    [Parameter(Mandatory)][string]$ApplicationId,
    [Parameter(Mandatory)][string]$ClientId,
    [int]$RedirectPort = 8765,
    [string]$Scope = 'openid',
    [int]$TimeoutSeconds = 300
)

try { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 } catch {}
Add-Type -AssemblyName System.Web

$identityBaseUrl       = "https://$IdentityTenantSubdomain.id.cyberark.cloud"
$privilegeCloudBaseUrl = "https://$PrivilegeCloudSubdomain.privilegecloud.cyberark.cloud/PasswordVault"
$redirectUri           = "http://127.0.0.1:$RedirectPort/callback"

# --- Preflight: catch the most common invalid_client cause ---
if ($ClientId -eq $ApplicationId) {
    Write-Host "WARNING: ClientId equals ApplicationId. These are usually different." -ForegroundColor Yellow
    Write-Host "         ClientId must match an entry under the app's 'Allowed Clients' (General Usage tab)." -ForegroundColor Yellow
    Write-Host "         invalid_client almost always means the client_id below is not registered.`n" -ForegroundColor Yellow
}

function ConvertTo-Base64Url([byte[]]$Bytes) {
    [Convert]::ToBase64String($Bytes).TrimEnd('=').Replace('+','-').Replace('/','_')
}
function New-CodeVerifier {
    $b = New-Object byte[] 64
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    ConvertTo-Base64Url $b
}
function Get-CodeChallenge([string]$Verifier) {
    $h = [System.Security.Cryptography.SHA256]::Create().ComputeHash([Text.Encoding]::ASCII.GetBytes($Verifier))
    ConvertTo-Base64Url $h
}
function ConvertFrom-JwtPayload([string]$Jwt) {
    try {
        $p = $Jwt.Split('.')[1].Replace('-','+').Replace('_','/')
        switch ($p.Length % 4) { 2 { $p += '==' } 3 { $p += '=' } }
        [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($p)) | ConvertFrom-Json
    } catch { $null }
}

$codeVerifier  = New-CodeVerifier
$codeChallenge = Get-CodeChallenge $codeVerifier
$state         = [guid]::NewGuid().ToString('N')

$authorizeUrl = "$identityBaseUrl/oauth2/authorize/$ApplicationId" +
    "?response_type=code&client_id=$([uri]::EscapeDataString($ClientId))" +
    "&redirect_uri=$([uri]::EscapeDataString($redirectUri))" +
    "&scope=$([uri]::EscapeDataString($Scope))" +
    "&code_challenge=$codeChallenge&code_challenge_method=S256&state=$state"

$listener = [System.Net.HttpListener]::new()
$listener.Prefixes.Add("http://127.0.0.1:$RedirectPort/")
try { $listener.Start() } catch { Write-Host "Cannot bind port $RedirectPort (in use, or needs a URL ACL / elevation)." -ForegroundColor Red; throw }

Write-Host "ClientId sent: |$ClientId|  (length $($ClientId.Length))" -ForegroundColor DarkGray
Write-Host "Authorize URL:`n$authorizeUrl`n" -ForegroundColor DarkGray
Write-Host "Opening browser for login (Azure AD + MFA)..." -ForegroundColor Cyan
Start-Process $authorizeUrl

$code = $null
$deadline = (Get-Date).AddSeconds($TimeoutSeconds)
$task = $listener.GetContextAsync()
while ((Get-Date) -lt $deadline) {
    if ($task.Wait(1000)) {
        $ctx = $task.Result
        $q   = [System.Web.HttpUtility]::ParseQueryString($ctx.Request.Url.Query)
        $buf = [Text.Encoding]::UTF8.GetBytes("You can close this window and return to PowerShell.")
        $ctx.Response.ContentLength64 = $buf.Length
        $ctx.Response.OutputStream.Write($buf, 0, $buf.Length)
        $ctx.Response.OutputStream.Close()
        if ($q['error'])            { Write-Host "Auth failed: $($q['error']) - $($q['error_description'])" -ForegroundColor Red; $listener.Stop(); return }
        if ($q['state'] -ne $state) { Write-Host "State mismatch. Aborting." -ForegroundColor Red; $listener.Stop(); return }
        $code = $q['code']; break
    }
}
$listener.Stop()
if (-not $code) { Write-Host "Timed out after $TimeoutSeconds s." -ForegroundColor Red; return }

$tokenBody = @{
    grant_type='authorization_code'; code=$code; redirect_uri=$redirectUri
    client_id=$ClientId; code_verifier=$codeVerifier
}
try {
    $token = Invoke-RestMethod -Method Post -Uri "$identityBaseUrl/oauth2/token/$ApplicationId" `
        -ContentType 'application/x-www-form-urlencoded' -Body $tokenBody -ErrorAction Stop
} catch {
    Write-Host "Token exchange failed." -ForegroundColor Red
    if ($_.ErrorDetails.Message) { Write-Host $_.ErrorDetails.Message -ForegroundColor Red }
    throw
}
if (-not $token.access_token) { Write-Host "No access_token returned." -ForegroundColor Red; return }
Write-Host "Access token acquired." -ForegroundColor Green

if ($token.id_token) {
    $c = ConvertFrom-JwtPayload $token.id_token
    if ($c) { Write-Host "Identity: $($c.email) ($($c.sub))" -ForegroundColor Cyan }
}

try {
    $safes = Invoke-RestMethod -Method Get -Uri "$privilegeCloudBaseUrl/api/Safes?limit=1" `
        -Headers @{ Authorization = "Bearer $($token.access_token)" } -ErrorAction Stop
    Write-Host "SUCCESS - token authenticated against Privilege Cloud." -ForegroundColor Green
    $safes | ConvertTo-Json -Depth 5 | Write-Host
} catch {
    switch ($_.Exception.Response.StatusCode.value__) {
        401 { Write-Host "401 - token rejected. App likely needs a Privilege Cloud scope/audience (Advanced tab), and request that scope." -ForegroundColor Yellow }
        403 { Write-Host "403 - auth works, but user role can't list Safes." -ForegroundColor Yellow }
        default { Write-Host "HTTP $($_.Exception.Response.StatusCode.value__): $($_.ErrorDetails.Message)" -ForegroundColor Red }
    }
}
