# Code Generated by Sidekick is for learning and experimentation purposes only.
$idc = ConvertFrom-JwtPayload $token.id_token
$atc = ConvertFrom-JwtPayload $token.access_token
Write-Host "`n--- ID token ---"      -ForegroundColor Cyan
Write-Host "  aud: $($idc.aud)`n  iss: $($idc.iss)"
Write-Host "--- Access token ---"     -ForegroundColor Cyan
Write-Host "  aud: $($atc.aud)`n  iss: $($atc.iss)"
