# Code Generated by Sidekick is for learning and experimentation purposes only.
$at = ConvertFrom-JwtPayload $token.access_token
if ($at) {
    Write-Host "`n--- Access token claims ---" -ForegroundColor Cyan
    Write-Host "  aud   : $($at.aud)"
    Write-Host "  scope : $($at.scope)"
    Write-Host "  iss   : $($at.iss)"
    Write-Host "  client_id : $($at.client_id)"
} else {
    Write-Host "Access token is opaque (not a JWT) - cannot decode locally." -ForegroundColor Yellow
}
